### PR TITLE
Touchegg 2.0.15

### PR DESCRIPTION
**Pull request by 13r0ck**
Please double check that my rebase didn't break https://github.com/pop-os/touchegg/pull/6

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — APPROVED** [review]
Looks good. Normal gestures are working as expected. This does not break anything from #6. I also tested with Touché (e.g., swapping left, right, up, down gestures) and it is working fine.

**Comment by 13r0ck** [comment]
@jackpot51 I don't have permissions to force push this rebase onto master

**Comment by jackpot51** [comment]
Pushed

**Comment by 13r0ck** [comment]
Thanks!

**Pull request merged**
