### PR TITLE
Update gesture function calls

### PR DESCRIPTION
**Pull request by jpttrssn**
Touchegg config changes required for https://github.com/pop-os/cosmic/pull/320

### CODE REVIEW

**Comment by jackpot51** [comment]
This branch is for 21.04, do you want to target 21.10 instead?

**Comment by jacobgkau** [comment]
Changed the base branch to master_impish and rebased/cherry-picked on top of master_impish. This was working before, will confirm it's still working now.

**Comment by jpttrssn** [comment]
Should be 21.10. My mistake. Thanks for taking care of that @jacobgkau. Let me know if you need me to do anything.

**Review by jacobgkau — APPROVED** [review]
Installing the update causes gestures to stop working until a reboot (restarting touchegg.service seems to bring them back as well). Not sure if that could be improved in the packaging, but that's not an issue with this PR.

Tested with https://github.com/pop-os/cosmic/pull/320.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
